import unittest

from structures import IZ


class PrimalityTest(unittest.TestCase):

    def test_aks(self):
        methods = ['aks', 'mr']
        for method in methods:
            self.assertTrue(IZ.is_prime(2, method=method), "easy test")
            self.assertTrue(IZ.is_prime(3, method=method), "easy test")
            self.assertTrue(IZ.is_prime(11, method=method), "easy test")
            self.assertTrue(IZ.is_prime(17, method=method), "easy test")
            self.assertTrue(IZ.is_prime(229, method=method), "medium test")
            self.assertFalse(IZ.is_prime(230, method=method), "medium test")
            self.assertFalse(IZ.is_prime(18354, method=method), "medium test")

    def test_generate_primes(self):
        for b in range(2, 10):
            p = IZ.get_random_prime(b)
            # It took up to 1min to finish but it works
            # (checking with 'aks' because prime was generated by using 'mr' already)
            self.assertTrue(p, IZ.is_prime(p, method='aks'))


if __name__ == '__main__':
    unittest.main()
